# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSerial1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(712, 545)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(510, 20, 191, 331))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.serialCOMComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialCOMComboBox.sizePolicy().hasHeightForWidth())
        self.serialCOMComboBox.setSizePolicy(sizePolicy)
        self.serialCOMComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.serialCOMComboBox.setEditable(False)
        self.serialCOMComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.serialCOMComboBox.setMinimumContentsLength(0)
        self.serialCOMComboBox.setObjectName("serialCOMComboBox")
        self.gridLayout.addWidget(self.serialCOMComboBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.serialBaudRateComboBox = QtWidgets.QComboBox(self.groupBox)
        self.serialBaudRateComboBox.setObjectName("serialBaudRateComboBox")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.gridLayout.addWidget(self.serialBaudRateComboBox, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.serialDataBitComboBox = QtWidgets.QComboBox(self.groupBox)
        self.serialDataBitComboBox.setObjectName("serialDataBitComboBox")
        self.serialDataBitComboBox.addItem("")
        self.serialDataBitComboBox.addItem("")
        self.serialDataBitComboBox.addItem("")
        self.serialDataBitComboBox.addItem("")
        self.gridLayout.addWidget(self.serialDataBitComboBox, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.serialStopBitComboBox = QtWidgets.QComboBox(self.groupBox)
        self.serialStopBitComboBox.setObjectName("serialStopBitComboBox")
        self.serialStopBitComboBox.addItem("")
        self.serialStopBitComboBox.addItem("")
        self.serialStopBitComboBox.addItem("")
        self.gridLayout.addWidget(self.serialStopBitComboBox, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.serialParityComboBox = QtWidgets.QComboBox(self.groupBox)
        self.serialParityComboBox.setObjectName("serialParityComboBox")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.gridLayout.addWidget(self.serialParityComboBox, 4, 2, 1, 1)
        self.openSerialButton = QtWidgets.QPushButton(self.groupBox)
        self.openSerialButton.setObjectName("openSerialButton")
        self.gridLayout.addWidget(self.openSerialButton, 5, 0, 1, 1)
        self.closeSerialButton = QtWidgets.QPushButton(self.groupBox)
        self.closeSerialButton.setObjectName("closeSerialButton")
        self.gridLayout.addWidget(self.closeSerialButton, 5, 1, 1, 2)
        self.refreshSerialButton = QtWidgets.QPushButton(self.groupBox)
        self.refreshSerialButton.setObjectName("refreshSerialButton")
        self.gridLayout.addWidget(self.refreshSerialButton, 6, 0, 1, 3)
        self.hexShowCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.hexShowCheckBox.setObjectName("hexShowCheckBox")
        self.gridLayout.addWidget(self.hexShowCheckBox, 7, 0, 1, 1)
        self.clearButtonReceive = QtWidgets.QPushButton(self.groupBox)
        self.clearButtonReceive.setObjectName("clearButtonReceive")
        self.gridLayout.addWidget(self.clearButtonReceive, 7, 1, 1, 2)
        self.timingSendCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.timingSendCheckBox.setObjectName("timingSendCheckBox")
        self.gridLayout.addWidget(self.timingSendCheckBox, 8, 0, 1, 2)
        self.timingLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.timingLineEdit.setObjectName("timingLineEdit")
        self.gridLayout.addWidget(self.timingLineEdit, 8, 2, 1, 1)
        self.hexSendCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.hexSendCheckBox.setObjectName("hexSendCheckBox")
        self.gridLayout.addWidget(self.hexSendCheckBox, 9, 0, 1, 2)
        self.sendNewLineCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.sendNewLineCheckBox.setObjectName("sendNewLineCheckBox")
        self.gridLayout.addWidget(self.sendNewLineCheckBox, 9, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 491, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.receiveTextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.receiveTextEdit.setGeometry(QtCore.QRect(10, 20, 471, 301))
        self.receiveTextEdit.setReadOnly(True)
        self.receiveTextEdit.setObjectName("receiveTextEdit")
        self.cntLabel = QtWidgets.QLabel(Form)
        self.cntLabel.setGeometry(QtCore.QRect(20, 520, 220, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntLabel.sizePolicy().hasHeightForWidth())
        self.cntLabel.setSizePolicy(sizePolicy)
        self.cntLabel.setMinimumSize(QtCore.QSize(220, 21))
        self.cntLabel.setMaximumSize(QtCore.QSize(240, 21))
        self.cntLabel.setObjectName("cntLabel")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 360, 691, 151))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.sendTextEdit = QtWidgets.QTextEdit(self.tab1)
        self.sendTextEdit.setGeometry(QtCore.QRect(10, 10, 561, 111))
        self.sendTextEdit.setTabStopWidth(80)
        self.sendTextEdit.setCursorWidth(5)
        self.sendTextEdit.setObjectName("sendTextEdit")
        self.sendButton = QtWidgets.QPushButton(self.tab1)
        self.sendButton.setGeometry(QtCore.QRect(590, 70, 81, 51))
        self.sendButton.setObjectName("sendButton")
        self.clearButtonSend = QtWidgets.QPushButton(self.tab1)
        self.clearButtonSend.setGeometry(QtCore.QRect(590, 10, 81, 31))
        self.clearButtonSend.setObjectName("clearButtonSend")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.layoutWidget = QtWidgets.QWidget(self.tab2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 591, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sendLineEdit1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit1.setObjectName("sendLineEdit1")
        self.gridLayout_3.addWidget(self.sendLineEdit1, 1, 0, 1, 1)
        self.sendButton2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton2.sizePolicy().hasHeightForWidth())
        self.sendButton2.setSizePolicy(sizePolicy)
        self.sendButton2.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton2.setObjectName("sendButton2")
        self.gridLayout_3.addWidget(self.sendButton2, 2, 1, 1, 1)
        self.sendLineEdit5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit5.setObjectName("sendLineEdit5")
        self.gridLayout_3.addWidget(self.sendLineEdit5, 1, 2, 1, 1)
        self.sendLineEdit6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit6.setObjectName("sendLineEdit6")
        self.gridLayout_3.addWidget(self.sendLineEdit6, 2, 2, 1, 1)
        self.sendButton0 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton0.sizePolicy().hasHeightForWidth())
        self.sendButton0.setSizePolicy(sizePolicy)
        self.sendButton0.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton0.setObjectName("sendButton0")
        self.gridLayout_3.addWidget(self.sendButton0, 0, 1, 1, 1)
        self.sendLineEdit0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit0.setObjectName("sendLineEdit0")
        self.gridLayout_3.addWidget(self.sendLineEdit0, 0, 0, 1, 1)
        self.sendLineEdit2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit2.setObjectName("sendLineEdit2")
        self.gridLayout_3.addWidget(self.sendLineEdit2, 2, 0, 1, 1)
        self.sendButton4 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton4.sizePolicy().hasHeightForWidth())
        self.sendButton4.setSizePolicy(sizePolicy)
        self.sendButton4.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton4.setObjectName("sendButton4")
        self.gridLayout_3.addWidget(self.sendButton4, 0, 3, 1, 1)
        self.sendButton7 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton7.sizePolicy().hasHeightForWidth())
        self.sendButton7.setSizePolicy(sizePolicy)
        self.sendButton7.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton7.setObjectName("sendButton7")
        self.gridLayout_3.addWidget(self.sendButton7, 3, 3, 1, 1)
        self.sendButton3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton3.sizePolicy().hasHeightForWidth())
        self.sendButton3.setSizePolicy(sizePolicy)
        self.sendButton3.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton3.setObjectName("sendButton3")
        self.gridLayout_3.addWidget(self.sendButton3, 3, 1, 1, 1)
        self.sendLineEdit3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit3.setObjectName("sendLineEdit3")
        self.gridLayout_3.addWidget(self.sendLineEdit3, 3, 0, 1, 1)
        self.sendButton6 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton6.sizePolicy().hasHeightForWidth())
        self.sendButton6.setSizePolicy(sizePolicy)
        self.sendButton6.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton6.setObjectName("sendButton6")
        self.gridLayout_3.addWidget(self.sendButton6, 2, 3, 1, 1)
        self.sendLineEdit4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit4.setObjectName("sendLineEdit4")
        self.gridLayout_3.addWidget(self.sendLineEdit4, 0, 2, 1, 1)
        self.sendLineEdit7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.sendLineEdit7.setObjectName("sendLineEdit7")
        self.gridLayout_3.addWidget(self.sendLineEdit7, 3, 2, 1, 1)
        self.sendButton1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton1.sizePolicy().hasHeightForWidth())
        self.sendButton1.setSizePolicy(sizePolicy)
        self.sendButton1.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton1.setObjectName("sendButton1")
        self.gridLayout_3.addWidget(self.sendButton1, 1, 1, 1, 1)
        self.sendButton5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton5.sizePolicy().hasHeightForWidth())
        self.sendButton5.setSizePolicy(sizePolicy)
        self.sendButton5.setMaximumSize(QtCore.QSize(30, 30))
        self.sendButton5.setObjectName("sendButton5")
        self.gridLayout_3.addWidget(self.sendButton5, 1, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab2)
        self.layoutWidget1.setGeometry(QtCore.QRect(610, 20, 77, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.importButton.setObjectName("importButton")
        self.verticalLayout.addWidget(self.importButton)
        self.outportButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.outportButton.setObjectName("outportButton")
        self.verticalLayout.addWidget(self.outportButton)
        self.tabWidget.addTab(self.tab2, "")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setGeometry(QtCore.QRect(541, 520, 150, 21))
        self.timeLabel.setMinimumSize(QtCore.QSize(150, 21))
        self.timeLabel.setMaximumSize(QtCore.QSize(200, 21))
        self.timeLabel.setObjectName("timeLabel")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.serialCOMComboBox, self.serialBaudRateComboBox)
        Form.setTabOrder(self.serialBaudRateComboBox, self.serialDataBitComboBox)
        Form.setTabOrder(self.serialDataBitComboBox, self.serialStopBitComboBox)
        Form.setTabOrder(self.serialStopBitComboBox, self.serialParityComboBox)
        Form.setTabOrder(self.serialParityComboBox, self.openSerialButton)
        Form.setTabOrder(self.openSerialButton, self.closeSerialButton)
        Form.setTabOrder(self.closeSerialButton, self.refreshSerialButton)
        Form.setTabOrder(self.refreshSerialButton, self.hexShowCheckBox)
        Form.setTabOrder(self.hexShowCheckBox, self.clearButtonReceive)
        Form.setTabOrder(self.clearButtonReceive, self.timingSendCheckBox)
        Form.setTabOrder(self.timingSendCheckBox, self.timingLineEdit)
        Form.setTabOrder(self.timingLineEdit, self.hexSendCheckBox)
        Form.setTabOrder(self.hexSendCheckBox, self.sendNewLineCheckBox)
        Form.setTabOrder(self.sendNewLineCheckBox, self.tabWidget)
        Form.setTabOrder(self.tabWidget, self.sendTextEdit)
        Form.setTabOrder(self.sendTextEdit, self.clearButtonSend)
        Form.setTabOrder(self.clearButtonSend, self.sendButton)
        Form.setTabOrder(self.sendButton, self.sendLineEdit0)
        Form.setTabOrder(self.sendLineEdit0, self.sendButton0)
        Form.setTabOrder(self.sendButton0, self.sendLineEdit1)
        Form.setTabOrder(self.sendLineEdit1, self.sendButton1)
        Form.setTabOrder(self.sendButton1, self.sendLineEdit2)
        Form.setTabOrder(self.sendLineEdit2, self.sendButton2)
        Form.setTabOrder(self.sendButton2, self.sendLineEdit3)
        Form.setTabOrder(self.sendLineEdit3, self.sendButton3)
        Form.setTabOrder(self.sendButton3, self.sendLineEdit4)
        Form.setTabOrder(self.sendLineEdit4, self.sendButton4)
        Form.setTabOrder(self.sendButton4, self.sendLineEdit5)
        Form.setTabOrder(self.sendLineEdit5, self.sendButton5)
        Form.setTabOrder(self.sendButton5, self.sendLineEdit6)
        Form.setTabOrder(self.sendLineEdit6, self.sendButton6)
        Form.setTabOrder(self.sendButton6, self.sendLineEdit7)
        Form.setTabOrder(self.sendLineEdit7, self.sendButton7)
        Form.setTabOrder(self.sendButton7, self.receiveTextEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "串口调试工具-V1.3"))
        self.groupBox.setTitle(_translate("Form", "串口配置"))
        self.label.setText(_translate("Form", "端口选择"))
        self.label_2.setText(_translate("Form", "波特率"))
        self.serialBaudRateComboBox.setItemText(0, _translate("Form", "2400"))
        self.serialBaudRateComboBox.setItemText(1, _translate("Form", "4800"))
        self.serialBaudRateComboBox.setItemText(2, _translate("Form", "9600"))
        self.serialBaudRateComboBox.setItemText(3, _translate("Form", "115200"))
        self.serialBaudRateComboBox.setItemText(4, _translate("Form", "460800"))
        self.label_3.setText(_translate("Form", "数据位"))
        self.serialDataBitComboBox.setItemText(0, _translate("Form", "5"))
        self.serialDataBitComboBox.setItemText(1, _translate("Form", "6"))
        self.serialDataBitComboBox.setItemText(2, _translate("Form", "7"))
        self.serialDataBitComboBox.setItemText(3, _translate("Form", "8"))
        self.label_4.setText(_translate("Form", "停止位"))
        self.serialStopBitComboBox.setItemText(0, _translate("Form", "1"))
        self.serialStopBitComboBox.setItemText(1, _translate("Form", "1.5"))
        self.serialStopBitComboBox.setItemText(2, _translate("Form", "2"))
        self.label_5.setText(_translate("Form", "奇偶校验位"))
        self.serialParityComboBox.setItemText(0, _translate("Form", "NONE"))
        self.serialParityComboBox.setItemText(1, _translate("Form", "EVEN"))
        self.serialParityComboBox.setItemText(2, _translate("Form", "ODD"))
        self.serialParityComboBox.setItemText(3, _translate("Form", "MARK"))
        self.serialParityComboBox.setItemText(4, _translate("Form", "SPACE"))
        self.openSerialButton.setText(_translate("Form", "打开串口"))
        self.closeSerialButton.setText(_translate("Form", "关闭串口"))
        self.refreshSerialButton.setText(_translate("Form", "刷新串口"))
        self.hexShowCheckBox.setText(_translate("Form", "Hex显示"))
        self.clearButtonReceive.setText(_translate("Form", "清除显示"))
        self.timingSendCheckBox.setText(_translate("Form", "定时发送/ms"))
        self.timingLineEdit.setText(_translate("Form", "1000"))
        self.hexSendCheckBox.setText(_translate("Form", "Hex发送"))
        self.sendNewLineCheckBox.setText(_translate("Form", "发送新行"))
        self.groupBox_2.setTitle(_translate("Form", "接收区"))
        self.cntLabel.setText(_translate("Form", "发送：65535 字节，接收：65536 字节"))
        self.sendButton.setText(_translate("Form", "发送"))
        self.clearButtonSend.setText(_translate("Form", "清除发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Form", "单条发送"))
        self.sendButton2.setText(_translate("Form", "2"))
        self.sendButton0.setText(_translate("Form", "0"))
        self.sendButton4.setText(_translate("Form", "4"))
        self.sendButton7.setText(_translate("Form", "7"))
        self.sendButton3.setText(_translate("Form", "3"))
        self.sendButton6.setText(_translate("Form", "6"))
        self.sendButton1.setText(_translate("Form", "1"))
        self.sendButton5.setText(_translate("Form", "5"))
        self.importButton.setText(_translate("Form", "导入条目"))
        self.outportButton.setText(_translate("Form", "导出条目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "多条发送"))
        self.timeLabel.setText(_translate("Form", "time:"))

import images_rc
